"""empty message

Revision ID: 412dc368a477
Revises: 
Create Date: 2018-05-27 00:07:45.246087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412dc368a477'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('album_name_key', 'album', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('album_name_key', 'album', ['name'])
    # ### end Alembic commands ###
